/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsRegNoRouteImport } from './routes/students.$regNo'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRegNoRoute = StudentsRegNoRouteImport.update({
  id: '/$regNo',
  path: '/$regNo',
  getParentRoute: () => StudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scholarships': typeof ScholarshipsRoute
  '/students': typeof StudentsRouteWithChildren
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scholarships': typeof ScholarshipsRoute
  '/students': typeof StudentsRouteWithChildren
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scholarships': typeof ScholarshipsRoute
  '/students': typeof StudentsRouteWithChildren
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scholarships' | '/students' | '/students/$regNo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scholarships' | '/students' | '/students/$regNo'
  id: '__root__' | '/' | '/scholarships' | '/students' | '/students/$regNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$regNo': {
      id: '/students/$regNo'
      path: '/$regNo'
      fullPath: '/students/$regNo'
      preLoaderRoute: typeof StudentsRegNoRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface StudentsRouteChildren {
  StudentsRegNoRoute: typeof StudentsRegNoRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsRegNoRoute: StudentsRegNoRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
